import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import "./globals.css";
import MainNav from "./components/Navbar/main-nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="font-cairo">
      <head>
        <link 
          href="https://fonts.googleapis.com/css2?family=Cairo:wght@200..1000&display=swap" 
          rel="stylesheet"
        />
      </head>
      
        <body className="antialiased">
          <MainNav/>
          {children}
        </body>
     
    </html>
  );
}
